services:
  syslog-ng:
    build: .
    container_name: syslog-ng
    volumes:
      - ./logs:/var/log/  
    restart: unless-stopped
    develop:
      watch:
        - path: ./rate_limit_test.conf 
          action: sync+restart
          target: /etc/syslog-ng/conf.d/rate_limit_test.conf 
        - path: ./rate_limiter.py
          action: sync+restart
          target: /usr/local/bin/rate_limiter.py